spring.datasource.url=jdbc:postgresql://delivery-db:5432/delivery
spring.datasource.username=${DB_USER:delivery}
spring.datasource.password=${DB_PASSWORD:delivery123}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
